# Change these first
owner: atmovantage # Your GitHub organization or username, where this repository lives
repo: atmostatus # The name of this repository

sites:
  - name: AtmoLive01 Server
    url: $ATMOLIVE01
  - name: AtmoLive02 Server
    url: $ATMOLIVE02
  - name: AtmoLive03 Server
    url: $ATMOLIVE03
  - name: AtmoLive04 Server
    url: $ATMOLIVE04
  - name: AtmoVantage Homepage
    url: https://atmovantage.com
  - name: AtmoVantage Support
    url: https://support.atmovantage.com/portal/en/home 
  - name: AtmoVantage Client Portal
    url: https://checkout.atmovantage.com/portal/atmovantage/login    
    
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.atmovantage.com
  # baseUrl: /your-repo-name
  logoUrl: https://atmovantage.com/wp-content/uploads/2019/04/Color-logo-Name-horizontal-small.png
  name: AtmoStatus
  introTitle: "**AtmoStatus** is the uptime monitor and status page for AtmoVantage."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
