# Change these first
owner: atmovantage # Your GitHub organization or username, where this repository lives
repo: atmostatus # The name of this repository

sites:
  - name: AtmoLive01 Server
    url: $ATMOLIVE01
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/cloudways_site_logo.png
  - name: AtmoLive02 Server
    url: $ATMOLIVE02
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/cloudways_site_logo.png
  - name: AtmoLive03 Server
    url: $ATMOLIVE03
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/cloudways_site_logo.png
  - name: AtmoLive04 Server
    url: $ATMOLIVE04
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/cloudways_site_logo.png
  - name: AtmoVantage Homepage
    url: https://atmovantage.com
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/atmovantage_logo-cloud-white.png
  - name: AtmoVantage Support
    url: https://support.atmovantage.com/portal/en/home
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/atmovantage_logo-cloud-white.png
  - name: AtmoVantage Client Portal
    url: https://checkout.atmovantage.com/portal/atmovantage/login
    maxResponseTime: 6000
    icon: https://atmovantage.com/wp-content/uploads/2021/08/atmovantage_logo-cloud-white.png
    
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.atmovantage.com
  # baseUrl: /your-repo-name
  logoUrl: https://atmovantage.com/wp-content/uploads/2019/04/Color-logo-Name-horizontal-small.png
  name: AtmoStatus
  theme: dark
  favicon: https://atmovantage.com/wp-content/uploads/2019/02/Color-logo-no-background-small.png
  introTitle: "**AtmoStatus** is the uptime monitor and status page for AtmoVantage."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://support.atmovantage.com/portal/en/home     
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
